# Generated by Django 5.1.2 on 2025-08-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('ka', 'Georgian'), ('en', 'English'), ('ru', 'Russian')], default='ka', max_length=2),
        ),
    ]
