# Generated by Django 5.1.2 on 2025-04-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('vefxistkaosani', 'ვეფხისტყაოსანი'), ('personage', 'პერსონაჟები'), ('opinions', 'ხალხის აზრები')], default='opinions', max_length=20),
        ),
    ]
