# Generated by Django 5.1.2 on 2025-08-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible_language',
            field=models.CharField(choices=[('all', 'All languages'), ('ka', 'Georgian'), ('en', 'English'), ('ru', 'Russian')], default='all', max_length=10),
        ),
    ]
